### ISSUE TITLE
github pages as showcase

### ISSUE THREAD

**Issue by Aluriak** [Aluriak/webclingo-example#17]
From #16 

Moving to github pages require `test_site` to be renamed `docs/` or to be moved in a gh-pages branch. The last looks not practical. The first is meh.

**Comment by Aluriak** [comment]
Yeah, solved by 969a7d167.

**Comment by Aluriak** [comment]
How to configure webpages to serve the website ? Currently set to «master branch /docs folder».

**Comment by domoritz** [comment]
It works for me now.

**Comment by Aluriak** [comment]
I have to agree with you now.

**Comment by domoritz** [comment]
Sweet. Do you want to add the url next to the repo description?

**Comment by Aluriak** [comment]
Oh, yes, i forgot about that !
