### ISSUE TITLE
Build for WebAssembly

### ISSUE THREAD

**Issue by domoritz** [Aluriak/webclingo-example#3]
I'd like to use clingo in modern browsers with WebAssembly. The [instructions](https://kripken.github.io/emscripten-site/docs/compiling/WebAssembly.html) say that I only need to pass `WASM=1` to `emcc`. Can you tell me where I need to add this option?

**Comment by Aluriak** [comment]
Well, i should have do that, but i did it bad. Now you have both my working `clingo.js` and `clingo.js.mem` in `debug/fedora24/`. 

I ran the WASM server as you propose in #6, and the compilation was completed without error. I however got the `ccall is not a function` error (see #2). WASM file is uploaded now.
