### ISSUE TITLE
Question about cmake call

### ISSUE THREAD

**Issue by domoritz** [Aluriak/webclingo-example#7]
What is https://github.com/Aluriak/webclingo-example/blob/master/compile_web.sh#L29 for? It causes issues when I don't ignore it on my machine. 

```
CMake Error: The source directory "/Users/domoritz/Developer/git/webclingo-example/clingo/build/web" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```

**Comment by Aluriak** [comment]
In my understanding, it makes cmake prepare the compilation files. I included it only because it was in emscripten documentation.

**Comment by Aluriak** [comment]
Ok, i get the error too. Thanks to your new flags, this is catched properly now.

On a fresh install however, this line do not raise any error, nor seems necessary.

**Comment by domoritz** [comment]
I tried a fresh install and get an error

```
...
+ mkdir -p build/web
+ cd build/web
+ cmake .
CMake Error: The source directory "/tmp/webclingo-example/clingo/build/web" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```

Could this be related to #2?
